### ISSUE TITLE
Failed running ccm start on osx

### ISSUE THREAD

**Issue by ronaldsuwandi** [riptano/ccm#483]
Tried running `ccm start` and I keep getting this exception

```
ccm start
[node1 ERROR] objc[51536]: Class JavaLaunchHelper is implemented in both /Library/Java/JavaVirtualMachines/jdk1.8.0_74.jdk/Contents/Home/bin/java and /Library/Java/JavaVirtualMachines/jdk1.8.0_74.jdk/Contents/Home/jre/lib/libinstrument.dylib. One of the two will be used. Which one is undefined.
Error: Could not find or load main class org.apache.cassandra.service.CassandraDaemon
```

Prior to that, I created cluster using the following command `ccm create -v 2.2.3 -n 4 mycluster`

```
~/W/ccm ☕️  ccm list
 *mycluster

~/W/ccm ☕️  ccm status
Cluster: 'mycluster'
--------------------
node1: DOWN (Not initialized)
node3: DOWN (Not initialized)
node2: DOWN (Not initialized)
node4: DOWN (Not initialized)

~/W/ccm ☕️  ifconfig lo0
lo0: flags=8049<UP,LOOPBACK,RUNNING,MULTICAST> mtu 16384
        options=3<RXCSUM,TXCSUM>
        inet6 ::1 prefixlen 128
        inet 127.0.0.1 netmask 0xff000000
        inet6 fe80::1%lo0 prefixlen 64 scopeid 0x1
        inet 127.0.0.2 netmask 0xff000000
        inet 127.0.0.3 netmask 0xff000000
        inet 127.0.0.4 netmask 0xff000000
        nd6 options=1<PERFORMNUD>
```

Anything I'm doing wrong? I installed Cassandra locally using homebrew, but I've killed the instance. Running on OSX 10.11.3 with Java8

**Comment by dins2k2** [comment]
Hi, 
Its a known JDK bug in Mac OSX. 
[bug.java.com](http://bugs.java.com/bugdatabase/view_bug.do?bug_id=8021205)
[bugs.openjdk.java.net](https://bugs.openjdk.java.net/browse/JDK-8022291)

As per the first bug link, its fixed in **JDK 7u60 (b01)**. Try reverting back to JDK 7 which works with current versions of C*.

Seems like bug is still unresolved in new versions of JDK as well.

Thanks,
Dinesh

**Comment by ptnapoleon** [comment]
You should still be able to compile and run C*, even with that message printed to stderr. What jdk version are you using, and what version of cassandra are you running? 

What happens when you compile your local C* installation (or is it already compiled)?

**Comment by ronaldsuwandi** [comment]
@dins2k2 thanks! reverting to jdk 7 is not really an option as i need jdk 8 for my work :-/

@ptnapoleon i'm using jdk 1.8.0_74, locally I have cassandra 2.2.3 running (installed from homebrew).

If I run `ccm start` it just keep giving me the exception and it got stuck

**Comment by ptnapoleon** [comment]
If you have C* 2.2.3 installed from homebrew, which is an interesting way to install C*, can you let me know if that works by itself? So just starting 2.2.3 out of your installation dir, without involving ccm?

**Comment by ronaldsuwandi** [comment]
@ptnapoleon yup, i've been using it for my work environment. Running it locally works fine (using `launchctl`)

I wanted to try ccm to complete DS201 course on datastax :-)

**Comment by dins2k2** [comment]
@ronaldsuwandi Why don't you install JDK7 as well and set the JDK7 path in CCM?

This [SOF link](http://stackoverflow.com/questions/26252591/mac-os-x-and-multiple-java-versions) will help you to manage/install multiple versions of JDK in Mac OS.

Thanks,
Dinesh

**Comment by ptnapoleon** [comment]
The error message 
```
Class JavaLaunchHelper is implemented in both /Library/Java/JavaVirtualMachines/jdk1.8.0_74.jdk/Contents/Home/bin/java and /Library/Java/JavaVirtualMachines/jdk1.8.0_74.jdk/Contents/Home/jre/lib/libinstrument.dylib. One of the two will be used. Which one is undefined.
```
has absolutely nothing to do with
```
Error: Could not find or load main class org.apache.cassandra.service.CassandraDaemon
```
which is the real problem. 
Can you run
```
ccm invalidatecache
ccm create -v 2.2.3 -n 1 test -s
```?
Then, if that fails, can you please share the contents of `~/.ccm/repository/last.log`?

**Comment by ronaldsuwandi** [comment]
@ptnapoleon yeah, that failed

```
~/W/ccm ☕️  ccm invalidatecache
~/W/ccm ☕️  ccm create -v 2.2.3 -n 1 test -s
Downloading http://archive.apache.org/dist/cassandra/2.2.3/apache-cassandra-2.2.3-src.tar.gz to /var/folders/q4/cy5k4x5n3fz3xgx2cb3_6ys40000gn/T/ccm-Qpl4hR.tar.gz (22.939MB)
  24053447  [100.00%]
Extracting /var/folders/q4/cy5k4x5n3fz3xgx2cb3_6ys40000gn/T/ccm-Qpl4hR.tar.gz as version 2.2.3 ...
Compiling Cassandra 2.2.3 ...
Traceback (most recent call last):
  File "/usr/local/Cellar/ccm/2.0.3/libexec/bin/ccm", line 72, in <module>
    cmd.run()
  File "/usr/local/Cellar/ccm/2.0.3/libexec/lib/python2.7/site-packages/ccmlib/cmds/cluster_cmds.py", line 126, in run
    cluster = Cluster(self.path, self.name, install_dir=self.options.install_dir, version=self.options.version, verbose=True)
  File "/usr/local/Cellar/ccm/2.0.3/libexec/lib/python2.7/site-packages/ccmlib/cluster.py", line 51, in __init__
    dir, v = self.load_from_repository(version, verbose)
  File "/usr/local/Cellar/ccm/2.0.3/libexec/lib/python2.7/site-packages/ccmlib/cluster.py", line 64, in load_from_repository
    return repository.setup(version, verbose)
  File "/usr/local/Cellar/ccm/2.0.3/libexec/lib/python2.7/site-packages/ccmlib/repository.py", line 40, in setup
    download_version(version, verbose=verbose, binary=binary)
  File "/usr/local/Cellar/ccm/2.0.3/libexec/lib/python2.7/site-packages/ccmlib/repository.py", line 206, in download_version
    compile_version(version, target_dir, verbose=verbose)
  File "/usr/local/Cellar/ccm/2.0.3/libexec/lib/python2.7/site-packages/ccmlib/repository.py", line 238, in compile_version
    ret_val = subprocess.call([platform_binary('ant'),'jar'], cwd=target_dir, stdout=lf, stderr=lf)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 522, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1334, in _execute_child
    child_exception = pickle.loads(data)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pickle.py", line 1382, in loads
    return Unpickler(file).load()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pickle.py", line 858, in load
    dispatch[key](self)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/pickle.py", line 966, in load_string
    raise ValueError, "insecure string pickle"
ValueError: insecure string pickle
```

log file is empty

**Comment by ptnapoleon** [comment]
Interesting. I have never seen this problem ever. Which version of python 2.7 are you on? How do you have ccm installed, from git or pypi?

**Comment by ronaldsuwandi** [comment]
I'm on python 2.7.11 - installed through homebrew.
ccm installed from homebrew as well (it comes built in from the cassandra brew).

Anyway I decided to use a virtual machine approach instead. I've got it working with ubuntu 14 on jdk8 running on virtualbox. Feel free to close the ticket or keep it open :-)
