### ISSUE TITLE
WSL Error - from ccsm

### ISSUE THREAD

**Issue by KsRyY** [riptano/ccm#700]
When I attempt to open the ccsm I got an error
```
/usr/lib/python2.7/dist-packages/gtk-2.0/gtk/__init__.py:57: GtkWarning: could not open display
  warnings.warn(str(e), _gtk.Warning)
Traceback (most recent call last):
  File "/usr/bin/ccsm", line 94, in <module>
    import ccm
  File "/usr/lib/python2.7/dist-packages/ccm/__init__.py", line 1, in <module>
    from ccm.Conflicts import *
  File "/usr/lib/python2.7/dist-packages/ccm/Conflicts.py", line 26, in <module>
    from ccm.Constants import *
  File "/usr/lib/python2.7/dist-packages/ccm/Constants.py", line 30, in <module>
    CurrentScreenNum = gtk.gdk.display_get_default().get_default_screen().get_number()
AttributeError: 'NoneType' object has no attribute 'get_default_screen'
```
Operating System: Ubuntu 18.04 - Windows Subsystem for Linux

**Comment by KsRyY** [comment]
Seems like `ccm` made this error

**Comment by KsRyY** [comment]
I have a guess about what happened, let me find out.

**Comment by KsRyY** [comment]
OK, It's just because I forgot to set `DISPLAY` enviroment variable
