### ISSUE TITLE
pip install ccm gives errror: "ImportError: No module named pathlib"

### ISSUE THREAD

**Issue by pluraltouch** [riptano/ccm#745]
Hi,

I have python 2.7.18 on RHEL 7.9, pip version 8.1.2, I've already installed pathlib2 via **pip install pathlib2** with success.
However **pip install ccm** gives the following error:

Any help appreciated

Collecting ccm
  Using cached https://files.pythonhosted.org/packages/f1/12/091e82033d53b3802e1ead6b16045c5ecfb03374f8586a4ae4673a914c1a/ccm-3.1.5.tar.gz
Collecting pyYaml (from ccm)
  Using cached https://files.pythonhosted.org/packages/36/2b/61d51a2c4f25ef062ae3f74576b01638bebad5e045f747ff12643df63844/PyYAML-6.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-I9s1ko/pyYaml/setup.py", line 67, in <module>
        import sys, os, os.path, pathlib, platform, shutil, tempfile, warnings
    ImportError: No module named pathlib

**Comment by pluraltouch** [comment]
This was early... Solved by **python -m pip install --upgrade "pip < 21.0"**

**Comment by tiagomlalves** [comment]
@pluraltouch do you think it would be valuable to add that information to https://github.com/riptano/ccm/blob/master/README.md ?

**Comment by pluraltouch** [comment]
I think pip version could qualify as a requirement, however I am not sure what would be the *minimum* expected pip version.

**Comment by tiagomlalves** [comment]
Use the latest version known to work (i.e. the one you used - that already helps)
